### PR TITLE
GraphQL Updates

### PR DESCRIPTION
**Pull request by radazen**
### Renamed some schema types
Apologies for the annoying refactor, but we were talking about users having multiple galleries recently, and I figured this would be a good time to standardize in case we need a `GalleryCollection` in the future to represent a gallery in a collection.
- GalleryNft -> CollectionNft
- GalleryCollection -> Collection
- GalleryCollectionLayout -> CollectionLayout
- GalleryCollectionLayoutInput -> CollectionLayoutInput

### New queries
- `nftById(id: DBID!)`
- `collectionNftById(nftId: DBID!, collectionId: DBID!)`

### New media subtype
Added `GltfMedia` as a `MediaSubtype`. We'll use this media type when we see a `.glb` or `.gltf` extension.

### Dataloader cache clearing
Any public API function that writes to the database will now clear all dataloader caches to ensure that we return the latest data to the caller.

### CODE REVIEW

**Review by Robinnnnn — APPROVED** [review]
🔥🔥🔥🔥🔥

**Comment by kaitoo1** [comment]
seeing this late but this is a great idea! 👏

**Comment by radazen** [comment]
> seeing this late but this is a great idea! 👏

On that topic: do you want me to keep tagging you as a reviewer on all this stuff? I left you out cause I figured you have enough stuff going on, but I'm happy to keep clicking your name when I put up PRs!

**Comment by kaitoo1** [comment]
that'd be great if you don't mind! i enjoy seeing your PRs and now that I'm learning to use graphql on the frontend it's extra useful to see these changes (plus I have more context to understand them)

**Comment by kaitoo1** [comment]
but definitely count me as an optional reviewer, don't want to block anything bc of timezone

**Pull request merged**
